// UI 레이아웃 상수
export const LAYOUT = {
  // UI 컴포넌트 높이 (Main + Renderer 공유) - Zen 스타일
  TAB_BAR_HEIGHT: 44,
  ADDRESS_BAR_HEIGHT: 56,
  TOOLBAR_HEIGHT: 100, // TAB_BAR + ADDRESS_BAR
  
  // 기타
  FRAME_PADDING: 8,
  BORDER_RADIUS: 12,
  SIDEBAR_WIDTH_COLLAPSED: 64,
  SIDEBAR_WIDTH_EXPANDED: 260,
  ANIMATION_DURATION: 200, // ms
  WINDOW_MIN_WIDTH: 1000,
  WINDOW_MIN_HEIGHT: 600,
  DEFAULT_WINDOW_WIDTH: 1400,
  DEFAULT_WINDOW_HEIGHT: 900
} as const

export const COLORS = {
  FRAME_BG: '#1a1a1a',
  SIDEBAR_BG: '#242424',
  TEXT_PRIMARY: '#ffffff',
  TEXT_SECONDARY: '#cccccc',
  BORDER: '#333333'
} as const
